export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USER_PROFILES = 'RECEIVE_USER_PROFILES';
export const RESET_AUTHED = 'RESET_AUTHED';
export const CREATE_USER = 'CREATE_USER';

export const CREATE_PAGE = 'CREATE_PAGE';
export const CREATE_COMPONENT = 'CREATE_COMPONENT';
export const DELETE_PAGE = 'DELETE_PAGE';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const READ_ALL_PAGE = 'READ_ALL_PAGE';
export const READ_PAGE = 'READ_PAGE';
