#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

spring.h2.console:
  enabled: true
  path: /h2-console

security:
  user:
    name: admin
    password: admin

  oauth2:
    client:
      client-id: foo
      client-secret: bar
    authorization:
#      check-token-access: isAuthenticated()
      token-key-access: isAuthenticated()

logging.level:
  org.springframework:
    security: debug
    boot: debug

server:
  port: 8081
