spring:
  datasource:
    url: jdbc:h2:file:~/.database/nanalog-api
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop

spring.h2.console:
  enabled: true
  path: /h2-console

security:
  user:
    name: admin
    password: admin
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
#      token-info-uri: http://localhost:8081/oauth/check_token
      jwt:
        key-uri: http://localhost:8081/oauth/token_key
