spring:
  datasource:
    url: jdbc:h2:file:~/.database/nanalog-api
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop